services:
  - type: web
    name: text-similarity-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.api.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
